"""Checks 1-4 and 12 of the Phase 1 plan:

  1-2. a config exists and produces a randomly initialised model
   3.   v001 is saved and published atomically
   4.   no pretrained neural weights were loaded
  12.   provenance is recorded

The check-4 tests are the load-bearing ones. "We did not load pretrained
weights" is a claim that is easy to make and easy to get wrong, so it gets
more evidence than any other requirement in the plan.
"""

from __future__ import annotations

import json
import math
import os
from pathlib import Path

import pytest
import torch

from conftest import no_network

from sma import arch, configs, proof, store


# =====================================================================
# 1-2. configuration and random initialisation
# =====================================================================


def test_3b_config_is_the_published_smollm3_architecture(official_config):
    """The 3B target must be the real SmolLM3, not an approximately-3B design.

    Asserted field by field, including the ones that are easy to forget and
    that silently change what gets trained.
    """
    expected = {
        "model_type": "smollm3",
        "hidden_size": 2048,
        "intermediate_size": 11008,
        "num_hidden_layers": 36,
        "num_attention_heads": 16,
        "num_key_value_heads": 4,
        "vocab_size": 128256,
        "max_position_embeddings": 65536,
        "rope_theta": 5000000.0,
        "no_rope_layer_interval": 4,
        "tie_word_embeddings": True,
        "attention_bias": False,
        "attention_dropout": 0.0,
        "rms_norm_eps": 1e-06,
        "hidden_act": "silu",
        "sliding_window": None,
        "use_sliding_window": False,
        "rope_scaling": None,
        "bos_token_id": None,
        "eos_token_id": 128001,
        "pad_token_id": 128004,
    }
    for key, value in expected.items():
        assert official_config[key] == value, f"config drift in {key}"


def test_class_defaults_differ_from_published_config():
    """Guards the trap this module exists to avoid.

    SmolLM3Config() defaults are max_position_embeddings=32768,
    rope_theta=2000000.0, bos_token_id=128000. Constructing from defaults
    rather than from the published file trains different RoPE with a spurious
    BOS token, and nothing raises. If a future transformers release ever makes
    the defaults match, this test starts failing and the workaround can retire.
    """
    from transformers import SmolLM3Config

    d = SmolLM3Config()
    assert d.max_position_embeddings != 65536
    assert d.rope_parameters["rope_theta"] != 5000000.0
    assert d.bos_token_id != None  # noqa: E711 — the published config sets null


def test_small_differs_from_3b_only_in_scale_fields():
    """Same architecture family, different scale.

    The small config is generated by overriding five fields, so this is a
    structural property rather than a promise — if someone adds a field to the
    small dict, this fails.
    """
    delta = configs.scale_delta("small")
    assert set(delta) == set(configs.SCALE_FIELDS), (
        f"small config changed non-scale fields: "
        f"{set(delta) - set(configs.SCALE_FIELDS)}"
    )
    for field in ("rope_theta", "no_rope_layer_interval", "vocab_size",
                  "tie_word_embeddings", "rms_norm_eps", "attention_bias",
                  "hidden_act", "attention_dropout"):
        assert configs.small_config_dict()[field] == configs.SMOLLM3_3B_OFFICIAL[field]


def test_small_preserves_nope_pattern():
    """NoPE every 4th layer is a real architectural feature of SmolLM3, not a
    detail. A small config that lost it would not be the same family."""
    report = arch.architecture_report("small")
    official = arch.architecture_report("3b")
    assert report["noRopeLayerInterval"] == official["noRopeLayerInterval"] == 4
    assert report["noRopeLayerIndices"] == [3, 7]
    assert official["noRopeLayerIndices"][:4] == [3, 7, 11, 15]
    assert report["layerTypes"] == ["full_attention"]


def test_head_dim_divisibility_is_enforced():
    """SmolLM3Config does not validate this; the attention layer derives
    head_dim and would fail deep inside SDPA instead."""
    from transformers import SmolLM3Config

    bad = SmolLM3Config(
        vocab_size=128256, hidden_size=384, intermediate_size=1024,
        num_hidden_layers=2, num_attention_heads=5, num_key_value_heads=1,
    )
    with pytest.raises(ValueError, match="divisible"):
        arch.assert_head_dim_divides(bad)


def test_expected_parameter_counts():
    """Counts are computed from the config, not quoted from a blog post."""
    assert configs.EXPECTED_PARAMS["small"] == 61_839_744
    assert configs.EXPECTED_PARAMS["3b"] == 3_075_098_624


def test_small_builds_expected_shape(small_model):
    model, config, sizes = small_model
    assert sizes["parametersUniqueByStorage"] == 61_839_744
    assert sizes["parametersTrainable"] == sizes["parametersTotal"], (
        "every parameter must be trainable — a frozen tensor is a bug"
    )
    assert model.config.vocab_size == 128_256
    assert len(model.model.layers) == 8


def test_init_is_deterministic_per_seed():
    torch.manual_seed(0)
    a, _, _ = arch.build_model("small", seed=0)
    b, _, _ = arch.build_model("small", seed=0)
    c, _, _ = arch.build_model("small", seed=1)
    sa, sb, sc = a.state_dict(), b.state_dict(), c.state_dict()
    assert all(torch.equal(sa[k], sb[k]) for k in sa), "same seed must reproduce"
    assert not all(torch.equal(sa[k], sc[k]) for k in sa), "different seed must differ"


def test_init_distribution_matches_initializer_range():
    """transformers 5.x uses a plain normal at std=initializer_range.

    Worth pinning: the docstring says "truncated normal" and the observed
    max is ~4.6 sigma, not 2. If this ever changes, the manifest's recorded
    initializer kind becomes wrong and must be updated with it.
    """
    model, config, _ = arch.build_model("small", seed=0)
    w = model.state_dict()["model.layers.0.mlp.gate_proj.weight"].float()
    assert w.std().item() == pytest.approx(0.02, rel=0.02)
    assert w.mean().item() == pytest.approx(0.0, abs=0.001)
    assert w.abs().max().item() > 0.04, "truncated at 2 sigma would cap near 0.04"


def test_norms_are_ones_and_no_biases(small_model):
    model, _, _ = small_model
    n = model.state_dict()["model.layers.0.input_layernorm.weight"].float()
    assert torch.allclose(n, torch.ones_like(n))
    assert not any(k.endswith("mlp.gate_proj.bias") for k in model.state_dict())


def test_tied_embedding_is_one_parameter():
    """tie_word_embeddings means one tensor, not two. The state dict aliases
    lm_head.weight onto model.embed_tokens.weight; counting entries instead of
    storages would report 111M and mask a real change to the embedding."""
    model, _, _ = arch.build_model("small", seed=0)
    total = sum({p.data_ptr(): p.numel() for p in model.parameters()}.values())
    assert total == 61_839_744
    if "lm_head.weight" in model.state_dict():
        e = model.state_dict()["model.embed_tokens.weight"]
        l = model.state_dict()["lm_head.weight"]
        assert e.untyped_storage().data_ptr() == l.untyped_storage().data_ptr()


# =====================================================================
# 3. save and atomic publish
# =====================================================================


def test_commit_writes_marker_and_is_atomic(tmp_root):
    with store.staging_dir(tmp_root, "v001") as tmp:
        store.write_json(tmp / "payload.json", {"a": 1})
        assert not (tmp_root / "v001").exists(), "must not be visible before commit"
    assert (tmp_root / "v001").exists()
    assert not store.is_committed(tmp_root / "v001")
    store.commit_marker(tmp_root / "v001", {"note": "test"})
    assert store.is_committed(tmp_root / "v001")
    assert store.read_json(tmp_root / "v001" / "COMMITTED")["note"] == "test"


def test_failed_stage_leaves_no_debris(tmp_root):
    with pytest.raises(RuntimeError):
        with store.staging_dir(tmp_root, "v002") as tmp:
            store.write_json(tmp / "partial.json", {})
            raise RuntimeError("build failed")
    assert not (tmp_root / "v002").exists()
    assert list(tmp_root.glob("*")) == []


def test_versions_are_immutable(tmp_root):
    with store.staging_dir(tmp_root, "v001"):
        pass
    store.commit_marker(tmp_root / "v001")
    with pytest.raises(FileExistsError):
        with store.staging_dir(tmp_root, "v001"):
            pass


def test_version_numbering_never_reuses(tmp_root):
    assert store.next_version(tmp_root) == "v001"
    for v in ("v001", "v002"):
        with store.staging_dir(tmp_root, v):
            pass
        store.commit_marker(tmp_root / v)
    assert store.next_version(tmp_root) == "v003"


# =====================================================================
# 4. no pretrained neural weights
# =====================================================================


def test_no_upstream_from_pretrained_in_model_path():
    audit = proof.audit_from_pretrained_usage(Path(__file__).resolve().parents[1] / "sma")
    assert audit["violations"] == [], (
        f"pretrained-weight loads found: {audit['violations']}"
    )


def test_auditor_ignores_docstrings_and_comments(tmp_path):
    """A text-scan auditor would flag its own documentation. Prove the ast
    implementation is not fooled."""
    module = tmp_path / "sma"
    module.mkdir()
    (module / "sneaky.py").write_text(
        'REPO = "HuggingFaceTB/SmolLM3-3B-Base"\n'
        "# from_pretrained('HuggingFaceTB/SmolLM3-3B-Base')\n"
        'DOC = """from_pretrained("HuggingFaceTB/SmolLM3-3B-Base")"""\n',
        encoding="utf-8",
    )
    (module / "real.py").write_text(
        "from transformers import AutoModelForCausalLM\n"
        "def load():\n"
        '    return AutoModelForCausalLM.from_pretrained("HuggingFaceTB/SmolLM3-3B-Base")\n',
        encoding="utf-8",
    )
    audit = proof.audit_from_pretrained_usage(module)
    assert len(audit["violations"]) == 1
    assert audit["violations"][0]["file"] == "real.py"
    assert audit["violations"][0]["line"] == 3


def test_loading_our_own_checkpoint_is_allowed(tmp_path):
    """from_pretrained is required to read a trained brain. Only bare Hub ids
    are violations — a filesystem path is how we reload v002."""
    module = tmp_path / "sma"
    module.mkdir()
    (module / "loader.py").write_text(
        "from transformers import AutoModelForCausalLM\n"
        "def load(p):\n"
        "    return AutoModelForCausalLM.from_pretrained(p)\n"
        'def load2():\n'
        '    return AutoModelForCausalLM.from_pretrained("data/models/v002")\n',
        encoding="utf-8",
    )
    audit = proof.audit_from_pretrained_usage(module)
    assert audit["violations"] == []
    assert len(audit["calls"]) == 2


def test_config_only_fetch_excludes_every_weight_pattern(tmp_root):
    assert not any("safetensors" in p for p in proof.CONFIG_ONLY_PATTERNS)
    assert not any(p.endswith(".bin") for p in proof.CONFIG_ONLY_PATTERNS)
    assert "config.json" in proof.CONFIG_ONLY_PATTERNS
    assert "tokenizer.json" in proof.CONFIG_ONLY_PATTERNS


@pytest.mark.slow
def test_real_fetch_downloads_no_weight_bytes(tmp_root):
    """End-to-end against the actual Hub, proving the allowlist holds.

    This is the only test that touches the network, and it asserts on bytes
    rather than filenames: a single shard fetched under any name would show up
    as weightBytes > 0.
    """
    info = proof.fetch_config_and_tokenizer(
        configs.ARCH_REFERENCE_REPO, tmp_root / "ref"
    )
    assert info["weightsDownloaded"] == []
    assert info["weightBytes"] == 0
    assert "config.json" in info["filesDownloaded"]
    assert "tokenizer.json" in info["filesDownloaded"]
    # hub bookkeeping under .cache/ must not pollute the manifest
    assert not any(f.startswith(".cache") for f in info["filesDownloaded"])
    # and the fetched config must be the real published 3B config
    fetched = json.loads(
        (Path(info["localDir"]) / "config.json").read_text(encoding="utf-8")
    )
    for key, value in configs.SMOLLM3_3B_OFFICIAL.items():
        assert fetched[key] == value, f"upstream {key} drifted from our source of truth"


def test_model_build_performs_no_network_access():
    """Structural proof: constructing from a config must not touch the network.

    Stronger than asserting an offline env var was set — if construction tried
    to fetch weights, this raises even on a machine with a warm cache.
    """
    with no_network():
        model, _, sizes = arch.build_model("small", seed=0)
    assert sizes["parametersUniqueByStorage"] == 61_839_744


def test_token_hashes_are_recorded(small_model):
    model, _, _ = small_model
    tensors = proof.tensor_hashes(model)["tensors"]
    assert len(tensors) == 76  # 74 parameters + 2 RoPE inverse-frequency buffers
    embed = tensors["model.embed_tokens.weight"]
    assert len(embed["sha256"]) == 64
    assert embed["numel"] == 128_256 * 384
    assert embed["dtype"] == "bfloat16"


def test_duplicate_hashes_at_init_are_expected(small_model):
    """Not every tensor has a distinct hash at initialisation, and asserting
    otherwise would be a false invariant.

    17 RMSNorm weights (two per layer plus the final norm) all initialise to
    exactly 1.0, and the two RoPE buffers hold identical values, so 76 tensors
    yield only 59 distinct digests. This is correct behaviour — but it means
    a version diff must compare tensor NAMES, never hash uniqueness, or a
    real change to one norm would be invisible among sixteen identical
    siblings.
    """
    model, _, _ = small_model
    tensors = proof.tensor_hashes(model)["tensors"]
    digests = [t["sha256"] for t in tensors.values()]
    assert len(digests) == 76
    assert len(set(digests)) == 59

    norm_names = [n for n in tensors if n.endswith("norm.weight")]
    assert len(norm_names) == 17  # 8 layers x 2 + final norm
    assert len({tensors[n]["sha256"] for n in norm_names}) == 1

    rope = [n for n in tensors if "inv_freq" in n]
    assert len(rope) == 2
    assert tensors[rope[0]]["sha256"] == tensors[rope[1]]["sha256"]


def test_seed_dependent_and_seed_invariant_tensors(small_model):
    """A precise, surprising split worth knowing before we write the
    training-diff test.

    Of 76 tensors, 57 depend on the seed. The other 19 do not: the 17 RMSNorm
    weights initialise to exactly 1.0 regardless of seed, and the 2 RoPE
    inverse-frequency buffers are a deterministic function of head_dim and
    rope_theta. Those 19 are byte-identical across every random seed.

    This does not threaten `test_every_tensor_differs_after_training` — both
    the norms and the buffers move once gradients reach them. It does mean a
    change-detection test written against *initialisation* would fail on 19 of
    76 tensors, and that "reseeding produces a different brain" holds for 57.
    """
    from sma import arch, proof

    a, _, _ = small_model
    other, _, _ = arch.build_model("small", seed=1)
    ta = proof.tensor_hashes(a)["tensors"]
    tb = proof.tensor_hashes(other)["tensors"]
    assert set(ta) == set(tb)

    changed = {n for n in ta if ta[n]["sha256"] != tb[n]["sha256"]}
    norms = {n for n in ta if n.endswith("norm.weight")}
    rope = {n for n in ta if "inv_freq" in n}
    assert len(norms) == 17  # 8 layers x 2 + final norm
    assert len(rope) == 2

    assert changed == set(ta) - norms - rope
    assert len(changed) == 57


def test_diff_must_be_computed_by_tensor_name(small_model):
    """A name-keyed diff, not a hash-set comparison.

    76 tensors occupy only 59 distinct digests: 17 norms collapse to one and
    2 RoPE buffers to another. Comparing digest sets therefore loses the
    name-to-tensor correspondence entirely — it can report that "something
    changed" but never which tensor, and two norms drifting to the same value
    would be invisible. The manifest is keyed by name precisely so that the
    v001->v002 diff can be read tensor by tensor.
    """
    from sma import arch, proof

    a, _, _ = small_model
    same, _, _ = arch.build_model("small", seed=0)
    other, _, _ = arch.build_model("small", seed=1)

    def changed(ta, tb):
        assert set(ta) == set(tb), "name sets must match before diffing"
        return {n for n in ta if ta[n]["sha256"] != tb[n]["sha256"]}

    ta = proof.tensor_hashes(a)["tensors"]
    ts = proof.tensor_hashes(same)["tensors"]
    to = proof.tensor_hashes(other)["tensors"]

    assert len(ta) == 76
    assert len({t["sha256"] for t in ta.values()}) == 59
    assert changed(ta, ts) == set(), "same seed moves nothing"
    assert len(changed(ta, to)) == 57


def test_tensor_hashes_change_with_seed(small_model):
    a, _, _ = small_model
    b, _, _ = arch.build_model("small", seed=1)
    ha = proof.tensor_hashes(a)["tensors"]["model.embed_tokens.weight"]["sha256"]
    hb = proof.tensor_hashes(b)["tensors"]["model.embed_tokens.weight"]["sha256"]
    assert ha != hb


def test_manifest_records_random_initialisation(small_model):
    model, config, sizes = small_model
    m = proof.build_manifest(
        config_name="small",
        version="v001",
        model=model,
        architecture=arch.architecture_report("small"),
        sizes=sizes,
        seed=0,
        dtype="bfloat16",
        structural_audit=proof.audit_from_pretrained_usage(
            Path(__file__).resolve().parents[1] / "sma"
        ),
    )
    assert m["initialisationType"] == "RANDOM"
    assert m["pretrainedWeightsUsed"] is False
    # The fallback records patterns we *requested*; a real fetch records only
    # files that exist upstream. Neither may ever name a weight artifact.
    assert not any(f.endswith(("safetensors", "bin", "pt")) for f in
                   m["configSource"]["filesDownloaded"])
    assert m["configSource"]["weightsDownloaded"] == []
    assert m["configSource"]["weightBytes"] == 0
    assert m["initializer"]["kind"] == proof.INITIALIZER_KIND
    assert m["initializer"]["std"] == 0.02
    assert "pretrained-artifact" in m["tokenizerSource"]
    assert m["sizes"]["parametersUniqueByStorage"] == 61_839_744


def test_manifest_persists_structural_audit_evidence(small_model):
    """The audit must live in the manifest, not only in the console reply.

    An init that printed "0 violations" while writing no evidence would leave
    nothing to re-verify later, which defeats the point of a provenance record.
    """
    model, _, sizes = small_model
    audit = proof.audit_from_pretrained_usage(
        Path(__file__).resolve().parents[1] / "sma"
    )
    assert audit["violations"] == []
    assert audit["calls"], "the audit must actually have scanned something"

    m = proof.build_manifest(
        config_name="small",
        version="v001",
        model=model,
        architecture=arch.architecture_report("small"),
        sizes=sizes,
        seed=0,
        dtype="bfloat16",
        structural_audit=audit,
    )
    assert m["structuralAudit"] == audit
    assert m["structuralAudit"]["violations"] == []


# ---- 4d. the loss signature ------------------------------------------


def test_expected_initial_loss_is_log_vocab():
    assert proof.expected_initial_loss(128_256) == pytest.approx(math.log(128_256))
    assert proof.expected_initial_loss(128_256) == pytest.approx(11.7618, abs=1e-4)


def test_loss_signature_guard_rejects_low_loss():
    """A pretrained SmolLM3 scores ~1.8-2.5. If a future vNNN ever evaluates
    that low, a weight leaked — this is the guard that notices."""
    with pytest.raises(AssertionError, match="pretrained weights leaked"):
        proof.check_loss_signature(2.1, 128_256)


def test_loss_signature_guard_rejects_hyperbolic_loss():
    with pytest.raises(AssertionError):
        proof.check_loss_signature(40.0, 128_256)


def test_measured_initial_loss_lands_in_band(small_model, tiny_corpus, tokenizer):
    """The empirical version of the same claim: run a real forward pass on a
    real corpus and confirm the loss is where an untrained model must be.

    This is the check that would catch a silently-pretrained model, because
    nothing else in the pipeline inspects the numbers.
    """
    model, config, _ = small_model
    ids = tokenizer(tiny_corpus, return_tensors="pt").input_ids[:, :128]
    with torch.no_grad():
        out = model(input_ids=ids, labels=ids)
    loss = float(out.loss)
    result = proof.check_loss_signature(loss, config.vocab_size)
    assert result["ok"]
    assert abs(result["deltaFromUniform"]) < 1.0
